import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>

      <Head>
        <title>Chatter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main>
        {/* sidebar */}
        {/* news feed */}
        {/* widgets */}
      </main>

    </div>
  )
}
